export const FETCH_ALL_PRODUCTS_REQUEST = 'FETCH_ALL_PRODUCTS_REQUEST'
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS'
export const FETCH_ALL_PRODUCTS_FAILURE = 'FETCH_ALL_PRODUCTS_FAILURE'
export const SEARCH_REQUEST='SEARCH_REQUEST'
export const SEARCH_SUCCESS='SEARCH_SUCCESS'
export const SEARCH_FAILURE='SEARCH_FAILURE'
export const ADD_TO_CART='ADD_TO_CART'
export const REMOVE_FROM_CART='REMOVE_FROM_CART'
export const CLEAR_CART='CLEAR_CART'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE'
export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST'


